---
version: '0.5' # Version of the KlovitClient instance
name: KlovitClient # Your Host's name
resource_type: 'GB' # This can be either GB or MB, NOTE:- If you have chosen GB then 100% cpu will be 1 thread, if you have chosen MB then 1 thread will be 100% cpu
website: 
  secret: "Website secret" # Randomize this as this will be the secret of the website for the session and middleware cookie
  url: https://localhost # URL of the dashboard
  port: '8081' # The port on which this KlovitClient instance will run
  description: The most reliable hosting # The description for your Hosting
  icon: https://docs.klovit.tech/img/Klovit%20Logo.png # Logo of your hosting
pterodactyl:
  url: 'http://localhost' # Your Pterodactyl Panel URL with "http://" or "https://"
  api: 'ptla_Hr0TVGzDe3PIgHL11uKtrQtbqflQSW9Cjw3RzaDAK2p' # Your Pterodactyl Panel Admin API Key
packages:
  default: default
  list:
    default:
      ram: 1 # Formatted according to "resource_type"
      disk: 2
      cpu: 2 # NOTE - If you have selected GB as resource_type, then 100% cpu is 1. If you have selected MB as resource_type then 100% cpu is 100
      servers: 1
auth:
  supabase: # REQUIRED
    supabase_url: '' # URL of your SupaBase Project
    supabase_anon_key: '' # Anon/API Key of your SupaBase Project
    oauth2:
      google:
        enabled: false
      github:
        enabled: false
      discord:
        enabled: false
database:
  type: 'sqlite' # Available types are 'sqlite' and 'mysql'
  sqlite: # ONLY CONFIGURE IS YOU HAVE DATABASE TYPE AS 'sqlite'
    sqlite_db_name: 'database.sqlite' # The database will be stored in './database/' directory
  mysql: # ONLY CONFIGURE IS YOU HAVE DATABASE TYPE AS 'mysql'
    mysql_db_name: 'klovitclient' # Your MYSQL DB name
    mysql_db_host: 'localhost' # Your MYSQL DB HOST
    mysql_db_port: '3306' # Your MYSQL DB PORT
    mysql_db_username: 'klovitclient' # Your MYSQL Username
    mysql_db_password:  'password@123' # You MYSQL password
locations:
  "1": # ID of the location on the pterodactyl panel
    name: Default Location 1 # Display name for the location
eggs:
  klovitegg: # KlovitClient's identifier of the egg
    display: MultiEgg | KlovitEgg # Display name of the egg
    limits: # formatted according to "resource_type"
      minimum: # The minimum resources a user can use while deploying a server
        ram: 1 
        disk: 1
        cpu: 1
      maximum: # The maximum resources a user can use while deploying a server
        ram: null
        disk: null
        cpu: null
      feature: # The limits on the following features
        databases: 1
        backups: 1
        allocations: 1
    info: # All this information can be found on the Egg's information page.
      egg: 34 # ID of the egg
      docker_image: ghcr.io/pterodactyl/yolks:java_17 # Docker image of the egg
      startup: bash install.sh && curl -Os "https://raw.githubusercontent.com/BeastGamer81/klovitegg/main/install.sh" # Startup command of the egg 
      environment: # Environment variables of the egg
        MINECRAFT_VERSION: latest
        PMMP_VERSION: PM5
        NODE_MAIN_FILE: index.js
coins:
  enabled: false
  store: # The cost and per is not intended to used with 0. This is not intended to sell resources for coins. Make sure coins are enabled too, or else there can be errors.
    enabled: false
    ram:
      cost: 1000 # Cost of the resource in coins
      per: 1 # Will be in the format according to "resource_type"
    disk:
      cost: 1000
      per: 1
    cpu:
      cost: 1000
      per: 1
    servers:
      cost: 100
      per: 1
